server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/todo_user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect