spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://configserver:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true